apiVersion: v1
kind: ConfigMap
metadata:
  name: nexushr-config
  labels:
    app: nexushr
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/nexushr"
  SPRING_DATASOURCE_USERNAME: "nexushr_user"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
  SECURITY_JWT_EXPIRATION_TIME: "86400000"
