apiVersion: v1
kind: Secret
metadata:
  name: nexushr-secrets
  labels:
    app: nexushr
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bmV4dXNocl9wYXNzd29yZA==   
  SECURITY_JWT_SECRET_KEY: <base64-of-a-NEW-randomly-generated-key>